version: '3.9'

services:
  nginx:
    image: techiearup/my-nginx:1.0
    depends_on:
      - web-1
      - web-2
    ports:
      - '8080:80'
  web-2:
    image: techiearup/my-docker-react-app:1.0
    ports:
      - '8081:3000'
  web-1:
    image: techiearup/my-docker-react-app:1.0
    ports:
      - '8082:3000'
