version: 2
jobs:
  build:
    working_directory: ~/Web
    docker:
      - image: circleci/node:16
        environment:
          NODE_ENV: 'development'
    steps:
      - run:
          name: 'Check Versions'
          command: |
            node --version
            yarn --version

      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: npm-cache-v1-{{ checksum "yarn.lock" }}

      - run: yarn global add lerna

      - run: npx lerna bootstrap

      - run:
          name: Run Tests
          command: npx lerna run test

      - run:
          name: Run Lint
          command: npx lerna run lint

      - save_cache:
          key: npm-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/.npm

workflows:
  version: 2
  build:
    jobs:
      - build
